# in mm
MIN_BOW_THICKNESS = 6.0
MAX_BOW_THICKNESS = 12.0
DEFAULT_BOW_THICKNESS = 8.0
MIN_GRIP_WIDTH = 25.0
MAX_GRIP_WIDTH = 36.0
DEFAULT_GRIP_WIDTH = 34.0
MIN_PALM_SIZE = 50.0
MAX_PALM_SIZE = 130.0
DEFAULT_PALM_SIZE = 90.0

# in relative units
MIN_BOW_CURVATURE = 0.2
MAX_BOW_CURVATURE = 0.4
DEFAULT_BOW_CURVATURE = 0.3
MIN_LIMB_STIFFNESS = 0.3
MAX_LIMB_STIFFNESS = 0.9
DEFAULT_LIMB_STIFFNESS = 0.6

# in m/s
MIN_LAUNCH_SPEED = 2.0
MAX_LAUNCH_SPEED = 7.0
DEFAULT_LAUNCH_SPEED = 4.0

# in N
MIN_DRAW_FORCE = 3.0
MAX_DRAW_FORCE = 29.0
DEFAULT_DRAW_FORCE = 8.0

# slider info
SLIDER_SCALE = 10.0
SINGLE_STEP_DISTANCE = 0.5  # in mm
SINGLE_STEP_STIFFNESS = 0.05  
SINGLE_STEP_CURVATURE = 0.01