# in mm
MIN_BOW_THICKNESS = 6.0
MAX_BOW_THICKNESS = 12.0
DEFAULT_BOW_THICKNESS = 8.0
MIN_GRIP_WIDTH = 25.0
MAX_GRIP_WIDTH = 36.0
DEFAULT_GRIP_WIDTH = 34.0
MIN_PALM_SIZE = 50.0
MAX_PALM_SIZE = 130.0
DEFAULT_PALM_SIZE = 90.0

# in relative units
MIN_BOW_CURVATURE = 0.2
MAX_BOW_CURVATURE = 0.4
DEFAULT_BOW_CURVATURE = 0.3
MIN_LIMB_STIFFNESS = 0.3
MAX_LIMB_STIFFNESS = 0.9
DEFAULT_LIMB_STIFFNESS = 0.6

# in m/s
MIN_LAUNCH_SPEED = 2.0
MAX_LAUNCH_SPEED = 7.0
DEFAULT_LAUNCH_SPEED = 4.0

# in N
MIN_DRAW_FORCE = 3.0
MAX_DRAW_FORCE = 29.0
DEFAULT_DRAW_FORCE = 8.0

# more draw force info
DEFAULT_DEFLECTION = 10.5  # mm
DEFAULT_YOUNGS_MODULUS = 3.700550  # E (N/mm^2) for PLA at infill density of 100% and layer height of 0.20 mm
DEFAULT_BEAM_THICKNESS = 0.6  # mm
DEFAULT_HEIGHT_DIFFERENCE_BETWEEN_BEAM_ENDS = 6.0  # mm
DEFAULT_EMPIRICAL_CORRECTIVE_FACTOR = 1000

# arrow info
MIN_ARROW_LENGTH = 45.0  # mm
MAX_ARROW_LENGTH = 80.0  # mm
DEFAULT_ARROW_LENGTH = 60.0  # mm
DEFAULT_ARROW_WEIGHT = 1.0  # g
DEFAULT_ARROW_TIP_DIAMETER = 8.0  # mm
DEFAULT_ARROW_TIP_LENGTH = 5.0  # mm
DEFAULT_DISTANCE_ARROW_PUSHED = 1.0  # mm

# slider info
SLIDER_SCALE = 10.0
SINGLE_STEP_DISTANCE = 0.5  # mm
SINGLE_STEP_STIFFNESS = 0.05  
SINGLE_STEP_CURVATURE = 0.01